
# COM11: ¿Qué mercados existen en un municipio?

PREFIX edintcom: <http://vocab.linkeddata.es/datosabiertos/def/comercio/censo-locales#>
PREFIX edintinf: <http://vocab.linkeddata.es/datosabiertos/def/urbanismos-infraestructuras/infraestructura#>
PREFIX esadm:    <http://vocab.linkeddata.es/datosabiertos/def/sector-publico/territorio#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT
       ?market
       ?marketLabel
WHERE {
  ?market a edintcom:CommercialAggregation ;
          edintinf:belongsTo <URI-MUNICIPIO> . #Por ejemplo, <http://datos.ejemplo.es/recurso/municipio/Madrid> .

  OPTIONAL {
    ?market rdfs:label ?marketLabel .
  }
}
ORDER BY ?marketLabel



# Variante con el número de puestos/comercio de cada mercado

PREFIX edintcom: <http://vocab.linkeddata.es/datosabiertos/def/comercio/censo-locales#>
PREFIX edintinf: <http://vocab.linkeddata.es/datosabiertos/def/urbanismos-infraestructuras/infraestructura#>
PREFIX esadm:    <http://vocab.linkeddata.es/datosabiertos/def/sector-publico/territorio#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>

SELECT
  ?market
  ?marketLabel
  (COUNT(DISTINCT ?commercialSpace) AS ?numComercios)
WHERE {
  ?market a edintcom:CommercialAggregation ;
          edintinf:belongsTo <URI-MUNICIPIO> . #Por ejemplo, <http://datos.ejemplo.es/recurso/municipio/Madrid> .

  OPTIONAL {
    ?commercialSpace a edintcom:CommercialSpace ;
                     edintcom:belongsToCommercialAggregation ?market .
  }

  OPTIONAL { ?market rdfs:label ?marketLabel }
}
GROUP BY ?market ?marketLabel
ORDER BY DESC(?numComercios)